# Generated by Django 4.0.4 on 2022-06-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_projects', '0003_add_extra_timecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups_formed',
            field=models.BooleanField(default=False, verbose_name='Группы сформированы'),
        ),
    ]
