# Generated by Django 4.0.4 on 2022-06-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_projects', '0004_project_groups_formed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number',
        ),
    ]
